spring:
  application:
    name: lecture-service

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        default_schema: lecture

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

resilience4j:
  circuitbreaker:
    instances:
      hub-server:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

server:
  port: 9005

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://${MONITORING_HOST:localhost}:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha