spring:
  application:
    name: mentoring-service

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

  profiles:
    include: kafka

resilience4j:
  circuitbreaker:
    instances:
      hub-server:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${MONITORING_HOST:localhost}:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 9006

eureka:
  client:
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}