topics:
  order:
    payment-pending: order.payment-pending.v1
    payment-canceled: order.payment-canceled.v1
    order-completed: order.completed.v1
    order-canceled: order.canceled.v1
    order-failed: order.failed.v1
    lecture-completed: order.lecture-completed.v1
    lecture-canceled: order.lecture-canceled.v1
    mentoring-completed: order.mentoring-completed.v1
    mentoring-canceled: order.mentoring-canceled.v1

  payment:
    confirmed: payment.confirmed.v1
    confirm-failed: payment.confirm-failed.v1
    canceled: payment.canceled.v1
    cancel-failed: payment.cancel-failed.v1

  booking:
    payment-completed: mentoring.booking.payment_completed.v1
    payment-failed: mentoring.booking.payment_failed.v1
    accepted: mentoring.booking.accepted.v1
    rejected: mentoring.booking.rejected.v1
    canceled: mentoring.booking.canceled.v1
    requested: mentoring.booking.requested.v1
    pending-approval: mentoring.booking.pending_approval.v1