# spring cloud loadbalancer
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    openfeign:
      circuitbreaker:
        enabled: true

# common Feign timeout setting
feign:
  client:
    default:
      connectTimeout: 5000
      readTimeout: 2000
      loggerLevel: full

# eureka server setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL1:localhost}:9001/eureka/,http://${EUREKA_SERVER_URL2:localhost}:9002/eureka/

# Actuator - refresh 엔드포인트 활성화 (무중단 설정 변경에 필수)
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

# swagger setting
springdoc:
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  paths-to-match:
    - /**

# 공통 로깅 레벨
logging:
  level:
    root: INFO