topics:
  order:
    payment-pending: order.payment-pending.v1
    payment-cancel: order.payment-cancel.v1
    notification-completed: order.notification-completed.v1
    notification-cancelled: order.notification-cancelled.v1
    lecture-completed: order.lecture-completed.v1
    lecture-cancelled: order.lecture-cancelled.v1
    mentoring-completed: order.mentoring-completed.v1
    mentoring-cancelled: order.mentoring-cancelled.v1

  payment:
    confirmed: payment.confirmed.v1
    failed: payment.failed.v1

  booking:
    payment-completed: mentoring.booking.payment_completed.v1
    payment-failed: mentoring.booking.payment_failed.v1
    accepted: mentoring.booking.accepted.v1
    rejected: mentoring.booking.rejected.v1
    canceled: mentoring.booking.canceled.v1
    requested: mentoring.booking.requested.v1
    pending-approval: mentoring.booking.pending_approval.v1