spring:
  application:
    name: user-service

  jpa:
    properties:
      hibernate:
        default_schema: users

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://keycloak.code-factory.co.kr/realms/spartahub/protocol/openid-connect/certs"
          issuer-uri: "https://keycloak.code-factory.co.kr/realms/spartahub"

# 키클록 설정
keycloak:
  server-url: "https://keycloak.code-factory.co.kr"
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

# 로그 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 9010

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
