spring:
  application:
    name: user-service

  jpa:
    properties:
      hibernate:
        default_schema: user_db

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9090/realms/goggles/protocol/openid-connect/certs"
          issuer-uri: "http://localhost:9090/realms/goggles"

keycloak:
  server-url: "http://localhost:9090"
  realm: goggles
  client-id: user-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 9010

